############################### 主题基本信息 ###############################
info:
  name: Volantis
  version: 1.7.3
  docs: https://volantis.js.org/
  cdn: # 要使用CDN，请在根目录的config文件中写上 use_cdn: true
    css:
    # style: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@1.7.3/css/style.css
    js:
      app: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@1.7.3/js/app.js
      search: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@1.7.3/js/search.js
      valine: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@1.7.3/js/valine.js



############################### 第三方插件 ###############################
# ⚠️ 注意：开启过多服务会导致网页加载缓慢、运行卡顿
plugins:
  # jquery是很多功能的基础，请勿关闭
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js
  ################################################## 提升速度类的服务
  # 鼠标放在链接上就提前开始加载了 [站内的url一定要以‘/’结尾]
  instant_page: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@1.7.3/js/instant_page.js
  ################################################## 优化体验类的服务
  # 图片放大预览
  fancybox:
    css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
    js: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
  # 页面滚动显示动画
  scrollreveal: #https://cdn.jsdelivr.net/npm/scrollreveal@4.0.5/dist/scrollreveal.min.js
  # 代码块复制按钮
  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
  ################################################## 运维服务
  # 访问量统计【加载非常缓慢】
  busuanzi: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js
  # 文章字数统计、阅读时长，开启需要安装插件: npm i --save hexo-wordcount
  wordcount: true
  ################################################## 美化类的服务
  # 按钮点击涟漪效果
  nodewaves:
    css: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.css
    js: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.js
  # 文本框打字机特效
  comment_typing: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@1.7.3/js/comment_typing.js



############################### 主题样式 ###############################
# 样式
style:
  # 卡片阴影效果
  shadow:
    # 导航栏阴影
    nav: true
    # 卡片阴影和悬浮动画
    # card: true
  # 毛玻璃效果 具体效果调整在： source/less/_color.less
  blur:
    navbar: true
    widget: true
    # body: true
# 建议：
#   有背景图：开启毛玻璃，关闭卡片阴影
#   无背景图：关闭毛玻璃，开启卡片阴影

# 显示「阅读全文」按钮
readmore: true

# 幻灯片背景
backstretch:
  enable: true          # 是否启用
  js: '//cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js'
  position: fixed       # cover: 封面背景   fixed: 整个网页背景
  duration: 20000       # 持续时间（毫秒）
  fade: 2500            # 渐变（毫秒）
  is_dark: #true        # 图片是否是暗色的（调整文字为白色）
  images:               # 我上传了一些高清壁纸到CDN中，仅限个人使用，商用后果自负！！！
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/41F215B9-261F-48B4-80B5-4E86E165259E.jpeg
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/BBC19066-E176-47C2-9D22-48C81EE5DF6B.jpeg
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B18FCBB3-67FD-48CC-B4F3-457BA145F17A.jpeg
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/00E0F0ED-9F1C-407A-9AA6-545649D919F4.jpeg
    # 下面这些建议 is_dark: true
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/67239FBB-E15D-4F4F-8EE8-0F1C9F3C4E7C.jpeg
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B951AE18-D431-417F-B3FE-A382403FF21B.jpeg
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/AEB33F9D-7294-4CF1-B8C5-3020748A9D45.jpeg
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/2884F904-F1F3-479E-AE27-5EBC291B63B0.jpeg
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/10A0FCE5-36A1-4AD0-8CF0-019259A89E03.jpeg
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/250662D4-5A21-4AAA-BB63-CD25CF97CFF1.jpeg
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/298468D7-E388-44A8-8CC5-8213BDC33CED.jpeg



############################### 自定义 ###############################
# page的封面
cover:
  scheme: search    # 后期将会提供多种封面布局方案
  height: full      # full: 首页封面占据整个第一屏幕，其他页面占半个屏幕高度， half: 所有页面都封面都只占半个屏幕高度
  title: YINUXY | 理想的生活就是生活的理想
  subtitle: WELCOME TO YINUXY'S BLOG
  logo: https://cdn.jsdelivr.net/gh/InfiniteYinux/cloud@2.23/mylogo/logo.png    # logo和title只显示一个，若同时设置，则只显示logo
  search: Please search here...
  # 主页封面菜单
  features:
    - name: 主页
      icon: fas fa-home
      url: /
    - name: 归档
      icon: fas fa-archive
      url: archives/
    - name: 分类
      icon: fas fa-folder-open
      url: categories/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 关于
      icon: fas fa-info-circle
      url: about/
      rel: nofollow

# 导航栏
navbar:
  # 左侧logo区
  logo:
    # 显示图片，使用图片时将不会显示icon和title
  # img: https://cdn.jsdelivr.net/gh/InfiniteYinux/cloud@2.33/mylogo/name.png
    # 显示图标
    icon: https://cdn.jsdelivr.net/gh/InfiniteYinux/cloud@master/favicon/favicon.ico
    # 显示标题
    title: YINUXY'S BLOG
  # logo后面的导航菜单
  menu:
    # 在桌面端显示的导航菜单
    on_desktop:
      - name: 主页
        icon: fas fa-home
        url: /
      - name: 归档
        icon: fas fa-archive
        url: archives/
        rel: nofollow
      - name: 分类
        icon: fas fa-folder-open
        url: categories/
        rel: nofollow
      - name: 标签
        icon: fas fa-tags
        url: tags/
        rel: nofollow
      - name: 留言
        icon: fas fa-comments
        url: comments/
      - name: 友链
        icon: fas fa-link
        url: friends/
        rel: nofollow
      - name: 导航
        icon: fas fa-map-signs
        url: box/
        rel: nofollow
      - name: 关于
        icon: fas fa-info-circle
        url: about/
        rel: nofollow
    # 手机端导航菜单（从右上角的按钮点击展开）
    on_mobile:
      - name: 近期文章
        icon: fas fa-clock
        url: /
      - name: 文章归档
        icon: fas fa-archive
        url: archives/
        rel: nofollow
      - name: 文章分类
        icon: fas fa-folder-open
        url: categories/
        rel: nofollow
      - name: 我的友链
        icon: fas fa-link
        url: friends/
        rel: nofollow
      - name: 欢迎留言
        icon: fas fa-comments fa-fw
        url: comments/
        rel: nofollow
      - name: 关于小站
        icon: fas fa-info-circle
        url: about/
        rel: nofollow
  search: Please search here...   # 搜索框文字



# 布局
layout: # 下面的内容可以写在 `blog/source/_data/layout.yml` 中
  # 文章列表多列布局
  multiple_columns: false # 部分浏览器不兼容，谨慎使用
  # 文章列表（主页、自定义的列表）布局
  on_list:
    # 列表中每一篇文章的meta信息
    meta: [title, author, date, category, wordcount, top]
    # 列表类页面的侧边栏
    sidebar: [blogger, dao_hang, huan_ying, WeChat, category, tagcloud]
  # 页面布局
  on_page:
    # 文章页面主体元素，你也可以在页面的Front-matter中设置
    body: [article, comments]
    # 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
    # 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
    # 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
    meta:
      header: [title, author, date, category, counter, wordcount, top]
      footer: [updated, tags, btns, share]
    # 文章页面的侧边栏
    sidebar: [blogger, toc, grid, category, tagcloud, related_posts]
  # 文章布局，参数继承自 on_page
  on_post:
    # 文章页脚，自动在每一篇文章末尾添加
    article_footer: [copyright] #, donate]
  # 其他的页面布局暂时等于 on_list


# meta库配置
meta:
  # 文章标题
  title: # 暂无配置
  # 默认文章作者（可在front-matter中覆盖）
  author:
    avatar: https://cdn.jsdelivr.net/gh/InfiniteYinux/cloud@master/avatar/avatar.png
    name: YINUXY
    url: https://blog.yinuxy.com
  # 文章创建日期
  date:
    icon: fas fa-calendar-alt
    title: '发布日期：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章更新日期
  updated:
    icon: fas fa-save
    title: '本页文档最后更新于：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章分类
  category:
    icon: fas fa-folder-open
  # 文章置顶
  top:
    icon: fas fa-angle-double-up
  # 文章浏览计数
  counter:
    icon: fas fa-eye
  # 文章字数和阅读时长
  wordcount:
    icon_wordcount: fas fa-keyboard
    icon_duration: fas fa-hourglass-half
  # 文章标签
  tags:
    icon: fas fa-tag
  # 分享
  share:
    - id: qq
      name: QQ好友
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qq.png
    - id: qzone
      name: QQ空间
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qzone.png
    - id: weibo
      name: 微博
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/weibo.png
  # - id: qrcode # 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
  #   name: QRcode
  # 链接
  btns:
    edit:
      icon: fas fa-edit
      title: 在GitHub上编辑此页
      color: '#888'
    repo: # 源码链接
      icon: fas fa-file-code
      title: 源码
      color: '#508EF2'
    bug: # BUG反馈链接
      icon: fas fa-bug
      title: BUG
      color: '#FE5F58'
    doubt: # 疑问链接
      icon: fas fa-question-circle
      title: 疑问
      color: '#FFBD2B'
    idea: # 建议链接
      icon: fas fa-lightbulb
      title: 建议
      color: '#3DC550'
    faq: # FAQ链接
      icon: fas fa-comments
      title: FAQ
      color: '#29B1C9'
    feedback: # 反馈链接
      icon: fas fa-comment-dots
      title: 反馈
      color: '#1BCDFC'

# 组件库配置
widget: # 下面的内容可以写在 `blog/source/_data/widget.yml` 中
  # ---------------------------------------
  # 博主信息小部件配置
  blogger:
    class: blogger
    display: [desktop] # [desktop, mobile]
    avatar: https://cdn.jsdelivr.net/gh/InfiniteYinux/cloud@master/avatar/avatar.png
    title: YINUXY'S BLOG
    subtitle: 不怕念起 就怕觉迟 理可顿悟 事须渐修
    jinrishici: # true # 今日诗词。可以设置字符串，加载失败时会显示占位字符串。
    social: true
  # ---------------------------------------
  # 目录小部件配置(仅在文章中有效)
  toc:
    class: toc
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-list
      title: 本文目录
    list_number: false # 是否显示章节
    min_depth: 2 # H1建议用作网页或者文章的标题，章节从H2开始。
    max_depth: 5 # 由于宽度有限，主题没有针对所有层级进行布局优化，建议文章最多分为：H2/H3/H4/H5四个层级
  # ---------------------------------------
  # daohang
  dao_hang:
    class: grid
    header:
      icon: fas fa-map-signs
      title: 站内导航
    rows:
      - name: 文章归档
        icon: fas fa-archive
        url: archives/
      - name: 所有分类
        icon: fas fa-folder-open
        url: categories/
      - name: 文章标签
        icon: fas fa-tags
        url: tags/
      - name: 歌单分享
        icon: fas fa-compact-disc
        url: https://music.163.com/#/user/home?id=641108605
      - name: RSS订阅
        icon: fas fa-rss
        url: /atom.xml
      - name: 我的友链
        icon: fas fa-link
        url: friends/
        rel: nofollow
  # ---------------------------------------
  # 欢迎语
  huan_ying: # 唯一标识，自己命名，建议全英文
    class: text # 小部件类型，对应_widget文件夹中的文件名
    header:
      icon: fas fa-handshake
      title: 欢迎光临
    content: 
    - '<center><font  size = "5" color = "#FFB6C1"  face = "楷体">欢</font><font  size = "5" color = "#FFC0CB"  face = "楷体">迎</font><font  size = "5" color = "#DC143C"  face = "楷体">光</font><font  size = "5" color = "#7B68EE "  face = "楷体">临</font><font  size = "5" color = "#DB7093"  face = "楷体">本</font><font  size = "5" color = "#FF69B4"  face = "楷体">站</center><center></font><font  size = "5" color = "#FF1493"  face = "楷体">如</font><font  size = "5" color = "#C71585"  face = "楷体">果</font><font  size = "5" color = "#DA70D6"  face = "楷体">对</font><font  size = "5" color = "#D8BFD8"  face = "楷体">您</font><font  size = "5" color = "#DDA0DD"  face = "楷体">有</font><font  size = "5" color = "#EE82EE"  face = "楷体">帮</font><font  size = "5" color = "#FF00FF"  face = "楷体">助</font><font  size = "5" color = "#FF00FF"  face = "楷体">的</font><font  size = "5" color = "#8B008B"  face = "楷体">话</center><center></font><font  size = "5" color = "#800080"  face = "楷体">记</font><font  size = "5" color = "#BA55D3"  face = "楷体">得</font><font  size = "5" color = "#9400D3"  face = "楷体">分</font><font  size = "5" color = "#9932CC"  face = "楷体">享</font><font  size = "5" color = "#4B0082"  face = "楷体">转</font><font  size = "5" color = "#8A2BE2"  face = "楷体">发</font><font  size = "5" color = "#9370DB"  face = "楷体">哦</font></center>'
  # ---------------------------------------
  # 公众号二维码
  WeChat: # 唯一标识，自己命名，建议全英文
    class: qrcode # 小部件类型，对应_widget文件夹中的文件名
    display: [desktop] # [desktop, mobile]
    header:
      icon: fab fa-weixin
      title: 微信公众号
    height: # 128px  # 不设置则自动高度
    fancybox: true # 是否允许点击放大
    images:
      - https://cdn.jsdelivr.net/gh/InfiniteYinux/cloud@master/qrcode.jpg
  # ---------------------------------------
  # 文章分类小部件配置
  category:
    class: category
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-folder-open
      title: 文章分类
      url: /categories/
  # ---------------------------------------
  # 标签云小部件配置
  tagcloud:
    class: tagcloud
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-tags
      title: 热门标签
      url: /tags/
    min_font: 14
    max_font: 24
    color: true
    start_color: '#999'
    end_color: '#555'
  # ---------------------------------------
  # 相关文章小部件配置
  related_posts:
    class: related_posts # 需要安装插件  npm i -S hexo-related-popular-posts
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-bookmark
      title: 相关文章
    max_count: 5
  # ---------------------------------------
  # 版权说明小部件（仅用于文章中）
  copyright:
    class: copyright
    display: [desktop, mobile] # [desktop, mobile]
    blockquote: true # 是否把内容放到blockquote中
    permalink: '本文永久链接是：' # 显示文章永久链接
    content:
      - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)<br> 如需转载请注明出处@[Copyright © 2019-2020 YINUXY](https://blog.yinuxy.com)'
      - ''
      - permalink
  # ---------------------------------------
  # 二维码小部件（可用于文章中的打赏，只显示图片，无其他功能）
  qrcode:
    class: qrcode
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-mobile
      title: 手机观看
    height: #64px  # 不设置则自动高度
    fancybox: #true # 是否允许点击放大
    images:
      - https://cdn.jsdelivr.net/gh/InfiniteYinux/cloud@master/qrcode.jpg
  # 打赏
  donate:
    class: text
    display: [desktop, mobile] # [desktop, mobile]
    content:
      - '<a id="github" href="https://github.com/TinyJay/donate-page" target="_blank" class="pos-f tr3" title="Github"></a>'
	    - '<div><center>您的支持，使我不懈努力！❤️</center></div>'
	    - '<div id="DonateText" class="tr3">Donate</div><ul id="donateBox" class="list pos-f tr3"><li id="PayPal"><a href="https://www.paypal.me/yyy711" target="_blank" title="PayPal付款页">PayPal</a></li><li id="AliPay" data-footnote="点击查看支付宝付款码"><a  title="支付宝付款码">AliPay</a></li><li id="WeChat" data-footnote="点击查看微信付款码"><a  title="微信付款码">WeChat</a></li><li id="QQPay" data-footnote="点击查看QQ付款码"><a  title="QQ付款码">QQPay</a></li></ul><div id="QRBox" class="pos-f left-100"><div id="MainBox"></div></div>'

# 网站页脚
footer:
  # 网站页脚布局，默认支持 aplayer/social/license/info/copyright
  layout: [aplayer, social] #, license, info, copyright]
  # APlayer配置 https://github.com/metowolf/MetingJS
  aplayer:
    # 是否启用，注释此项则不加载服务
    enable: true
    # 必选参数
    server: netease   # netease, tencent, kugou, xiami, baidu
    type: playlist    # song, playlist, album, search, artist
    id: 987444580    # song id / playlist id / album id / search keyword
    # 可选参数
    fixed: true      # enable fixed mode
    theme: '#1BCDFC'  # main color
    autoplay: false   # audio autoplay
    order: list       # player play order, values: 'list', 'random'
    loop: all         # player loop play, values: 'all', 'one', 'none'
    volume: 0.7       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    list_max_height: 340px # list max height
    list_folded: true
  # 社交信息配置
  social:
    - icon: fas fa-rss
      url: atom.xml
    - icon: fas fa-envelope
      url: mailto:1154418252@qq.com
    - icon: fab fa-qq
      url: http://wpa.qq.com/msgrd?v=3&amp;uin=1154418252&amp;site=qq&amp;menu=yes
    - icon: fab fa-github
      url: https://github.com/InfiniteYinux
    - icon: fas fa-headphones-alt
      url: https://music.163.com/#/user/home?id=641108605
  copyright: '[Copyright © 2019-2020 YINUXY](https://blog.yinuxy.com)'
  # 可自己增加任意属性，支持markdown，例如：br: '<br>'
  br: '<br>'



seo:
  # 当文章front-matter中没有keywords时，使用tags作为keywords
  use_tags_as_keywords: true
  # 当文章front-matter中没有description时，使用摘要作为description
  use_excerpt_as_description: true
  robots:
    home_first_page: index,follow
    home_other_pages: noindex,follow
    archive: noindex,follow
    category: noindex,follow
    tag: noindex,follow
# 其它页面自己在front-matter中写


####################################### 友链页头像占位图 #######################################
avatar_placeholder: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/images/bitmap.gif

############################### # Reward ###############################

reward:
  enable: true
  reward_comment: 您的支持，使我不懈努力！❤️
  PayPalLink: https://paypal.me/yyy7111
  AliPayOR: https://cdn.jsdelivr.net/gh/InfiniteYinux/cloud@2.36/donate/alipay.png
  WeChatPayOR: https://cdn.jsdelivr.net/gh/InfiniteYinux/cloud@2.36/donate/wechat.png
  QQPayOR: https://cdn.jsdelivr.net/gh/InfiniteYinux/cloud@2.36/donate/qq.png


############################### 评论系统 ###############################
# disqus_shortname: 要使用哪个请复制到根目录配置文件！
# livere_uid: 要使用哪个请复制到根目录配置文件！
# gitalk: 要使用哪个请复制到根目录配置文件！
#   clientID: 你的clientID
#   clientSecret: 你的clientSecret
#   repo: 你的repo名
#   owner: 你的GitHub名
#   admin: [] 至少填写你的GitHub名
# leancloud: 要使用哪个请复制到根目录配置文件！
#   app_id: 你的appId
#   app_key: 你的appKey


############################### 杂项，请勿删除 ###############################
############################### 杂项，请勿删除 ###############################
############################### 杂项，请勿删除 ###############################

############################### 杂项，请勿删除 ###############################
#valine配置
valine:
  enable: true # 如果你想用Valine评论系统，请设置enable为true
  # 还需要在根目录配置文件中添加下面这三行内容
  leancloud:
    app_id: kISuzf8thVesufx29NhqXTwU-gzGzoHsz
    app_key: TW2Yq6YcP29dgWbQrGMzMApR
  #   valine_path: 全站采用同一个path（共用同一个评论框数据）
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: true # valine verify code (true/false)
  notify: true # valine mail notify (true/false)
  lang: zh-cn
  highlight: true
  visitor: false # 阅读统计，按照官网文档接入了，但是依然不能用。

# 搜索配置
search:
  enable: true
  service: hexo    # 类型：google, algolia, azure, baidu 默认 hexo
# 选择你选取的搜索服务后，复制相应的配置到根目录配置文件中
# google:
#   apiKey:
#   engineId:
# algolia:
#   applicationID:
#   apiKey:
#   indexName:
# azure:
#   serviceName:
#   indexName:
#   queryKey:
# baidu:
#   apiId:

# Less渲染
less:
  compress: true
